### ISSUE TITLE
Roadmap переводов книг

### ISSUE THREAD

**Issue by funkill** [rust-lang-ru/books#5]
- [x] Async Book - rust-lang-ru/books#10
- [x] The Rust Programming Language - rust-lang-ru/books#11
- [ ] The Rustonomicon - rust-lang-ru/books#9
- [ ] Too Many Linked Lists - rust-lang-ru/books#8
- [ ] The Little Book of Rust Macros - rust-lang-ru/books#6
- [ ] Cargo doc - rust-lang-ru/books#7
- [ ] Rust Cookbook - rust-lang-ru/books#4
- [ ] The Edition Guide - rust-lang-ru/books#3
- [ ] The Embedded Rust Book - rust-lang-ru/books#2
- [ ] The WASM book - rust-lang-ru/books#1
